### ISSUE TITLE
Dependency: python 3.11 will require min pydantic 1.10 or a workaround

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/pydantic-openapi-schema#11]
In Python `3.11` `inspect.Parameter` raises `ValueError` where a parameter name is a keyword (see https://github.com/python/cpython/issues/92062).

We at least have `Schema` that triggers this error due to pydantic trying to create the aliases as parameters for the model signature, but there might be more too.

```python
class Schema(BaseModel):
    schema_not: Optional[Union[Reference, "Schema"]] = Field(default=None, alias="not")
    schema_if: Optional[Union[Reference, "Schema"]] = Field(default=None, alias="if")
```

PR that resolves from the pydantic end is merged and available in the 1.10 pre-releases: https://github.com/pydantic/pydantic/pull/4012.

I suppose we'll need a minimum 1.10 version constraint for pydantic based on the python version >=3.11

**Comment by Goldziher** [comment]
a constraint is going to be fine IMO
