### ISSUE TITLE
Allow to enable alias for OpenAPI310PydanticSchema

### ISSUE THREAD

**Issue by manycoding** [starlite-api/pydantic-openapi-schema#14]
I use a pydantic model to serialize some data and return as a response. Some fields have alias.

The problem is that `OpenAPI310PydanticSchema` always returns property names taken from alias, while default is False. So there's a mismatch between the actual output and OpenAPI310PydanticSchema when by_alias is False (default)

**Comment by Goldziher** [comment]
examples please

**Comment by manycoding** [comment]
```

from pydantic import BaseModel, Field
from pydantic_openapi_schema.utils.utils import (
    OpenAPI310PydanticSchema,
    construct_open_api_with_schema_class,
)
from pydantic_openapi_schema.v3_1_0 import OpenAPI


class User(BaseModel):
    id: int
    name: str = Field(alias="Another")


User(id=0, Another="name").dict() # returns name, all good
parameters = [
    {
        "name": "id",
        "in": "path",
        "description": "ID of the document",
        "required": True,
        "style": "simple",
        "explode": False,
        "schema": {"type": "integer", "format": "int64"},
    }
]
get_object = dict(
    # parameters=parameters,
    responses={
        "200": dict(
            description="response.",
            content={"application/json": dict(schema=OpenAPI310PydanticSchema(schema_class=User))},
        )
    },
)
info = dict(
    title="API",
    version="1.0",
    description=""
)
base_schema = dict(
    info=info,
    paths={},
        paths={"/document/{document_id}": {"get": get_object}}

)


construct_open_api_with_schema_class(OpenAPI.parse_obj(base_schema))
construct_open_api_with_schema_class(OpenAPI.parse_obj(base_schema)).dict(by_alias=False, exclude_none=True)
```
It returns `Another` as property name, while should be `name`

**Comment by Goldziher** [comment]
I see. So it doesn't propagate the alias true. 

Want to add a PR?

**Comment by manycoding** [comment]
It does not propagate alias true or false for passed `OpenAPI310PydanticSchema`.
`construct_open_api_with_schema_class` returns `OpenAPI` which has its own aliases like `$ref` > `ref` which shouldn't be touched.

If you point me to where do you think it should be changed, I can do it

**Comment by Goldziher** [comment]
well, you can add optional kwargs to `construct_open_api_with_schema_class` and propagate these to the `OpenAPI310PydanticSchema` class. Or you can update the `OpenAPI310PydanticSchema` with a config that favors aliases.
