### ISSUE TITLE
Generate mkdocstrings docs

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/pydantic-openapi-schema#2]
This will allow us to import the inventory into the starlite reference docs and cross reference to these docs.

See https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories

**Comment by Goldziher** [comment]
We can generate an mkdocs website as well if we want, but we need to write docs for this purpose 😉

**Comment by peterschutt** [comment]
Absolutely. Maybe this library would better suit the automated reference docs pattern that I had in starlite before reverting back to the manual approach. Even if they weren't perfect they'd be better than nothing and would keep themselves in check.

Also then might be able to have a landing page on `https://starlite-api.github.io/` that has links to all the org project docs - at the moment it just 404s and is something I've been keen to do something about.

**Comment by Goldziher** [comment]
Sounds good to me
